name: Deploy React App to GitHub Pages

on:
  push:
    branches: ['main'] # Remplace par 'master' si ta branche s'appelle master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    # Indique à GitHub Actions de travailler dans le sous-dossier portfolio-web
    defaults:
      run:
        working-directory: ./portfolio-web

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installer les dépendances
        run: npm install

      - name: Générer le build React
        run: npm run build

      - name: Uploader l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './portfolio-web/dist'

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4